#ifndef CONFIG_H
#define CONFIG_H

// Data collection intervals (milliseconds)
#define OBD_INTERVAL 1000      // OBD data collection interval
#define GPS_INTERVAL 2000      // GPS data collection interval  
#define MEMS_INTERVAL 500      // MEMS data collection interval
#define BLE_INTERVAL 1000      // BLE data transmission interval

// Storage settings
#define STORAGE_SIZE 1024      // Storage buffer size
#define MAX_LOG_ENTRIES 100    // Maximum log entries to keep

// BLE settings
#define BLE_DEVICE_NAME "FreematicsCustom"
#define BLE_SERVICE_UUID "12345678-1234-1234-1234-123456789abc"

// Debug settings
#define DEBUG_ENABLED 1
#define SERIAL_BAUDRATE 115200

// Pin definitions (adjust based on your hardware)
#define PIN_LED 2
#define PIN_BUZZER 25

// Standard OBD-II PIDs (Mode 01 - Current Data)
// Engine Management
#define PID_ENGINE_LOAD 0x04
#define PID_COOLANT_TEMP 0x05
#define PID_SHORT_TERM_FUEL_TRIM_1 0x06
#define PID_LONG_TERM_FUEL_TRIM_1 0x07
#define PID_SHORT_TERM_FUEL_TRIM_2 0x08
#define PID_LONG_TERM_FUEL_TRIM_2 0x09
#define PID_FUEL_PRESSURE 0x0A
#define PID_INTAKE_MAP 0x0B
#define PID_RPM 0x0C
#define PID_SPEED 0x0D
#define PID_TIMING_ADVANCE 0x0E
#define PID_INTAKE_TEMP 0x0F
#define PID_MAF_FLOW 0x10
#define PID_THROTTLE_POS 0x11

// Emissions & Fuel System
#define PID_O2_S1_VOLTAGE 0x14
#define PID_O2_S2_VOLTAGE 0x15
#define PID_O2_S3_VOLTAGE 0x16
#define PID_O2_S4_VOLTAGE 0x17
#define PID_O2_S5_VOLTAGE 0x18
#define PID_O2_S6_VOLTAGE 0x19
#define PID_O2_S7_VOLTAGE 0x1A
#define PID_O2_S8_VOLTAGE 0x1B
#define PID_OBD_STANDARDS 0x1C
#define PID_O2_SENSORS_PRESENT 0x1D
#define PID_AUX_INPUT 0x1E
#define PID_RUNTIME 0x1F

// Advanced Engine Parameters
#define PID_DISTANCE_WITH_MIL 0x21
#define PID_FUEL_RAIL_PRESSURE 0x22
#define PID_FUEL_RAIL_GAUGE_PRESSURE 0x23
#define PID_O2_S1_WR_VOLTAGE 0x24
#define PID_O2_S2_WR_VOLTAGE 0x25
#define PID_O2_S3_WR_VOLTAGE 0x26
#define PID_O2_S4_WR_VOLTAGE 0x27
#define PID_O2_S5_WR_VOLTAGE 0x28
#define PID_O2_S6_WR_VOLTAGE 0x29
#define PID_O2_S7_WR_VOLTAGE 0x2A
#define PID_O2_S8_WR_VOLTAGE 0x2B
#define PID_COMMANDED_EGR 0x2C
#define PID_EGR_ERROR 0x2D
#define PID_COMMANDED_EVAP_PURGE 0x2E
#define PID_FUEL_TANK_LEVEL 0x2F

// Emissions Control
#define PID_WARMUPS_SINCE_CODES_CLEARED 0x30
#define PID_DISTANCE_SINCE_CODES_CLEARED 0x31
#define PID_EVAP_SYS_VAPOR_PRESSURE 0x32
#define PID_ABSOLUTE_BAROMETRIC_PRESSURE 0x33
#define PID_O2_S1_WR_CURRENT 0x34
#define PID_O2_S2_WR_CURRENT 0x35
#define PID_O2_S3_WR_CURRENT 0x36
#define PID_O2_S4_WR_CURRENT 0x37
#define PID_O2_S5_WR_CURRENT 0x38
#define PID_O2_S6_WR_CURRENT 0x39
#define PID_O2_S7_WR_CURRENT 0x3A
#define PID_O2_S8_WR_CURRENT 0x3B
#define PID_CATALYST_TEMP_B1S1 0x3C
#define PID_CATALYST_TEMP_B2S1 0x3D
#define PID_CATALYST_TEMP_B1S2 0x3E
#define PID_CATALYST_TEMP_B2S2 0x3F

// Advanced Diagnostics
#define PID_CONTROL_MODULE_VOLTAGE 0x42
#define PID_ABSOLUTE_LOAD_VALUE 0x43
#define PID_FUEL_AIR_COMMANDED_EQUIV_RATIO 0x44
#define PID_RELATIVE_THROTTLE_POS 0x45
#define PID_AMBIENT_AIR_TEMP 0x46
#define PID_ABSOLUTE_THROTTLE_POS_B 0x47
#define PID_ABSOLUTE_THROTTLE_POS_C 0x48
#define PID_ACCELERATOR_PEDAL_POS_D 0x49
#define PID_ACCELERATOR_PEDAL_POS_E 0x4A
#define PID_ACCELERATOR_PEDAL_POS_F 0x4B
#define PID_COMMANDED_THROTTLE_ACTUATOR 0x4C
#define PID_TIME_WITH_MIL_ON 0x4D
#define PID_TIME_SINCE_CODES_CLEARED 0x4E
#define PID_MAX_VALUES_EQUIV_RATIO 0x4F

// Fuel System & Air Flow
#define PID_MAX_VALUES_AIR_FLOW_MAF 0x50
#define PID_FUEL_TYPE 0x51
#define PID_ETHANOL_FUEL_PERCENT 0x52
#define PID_ABSOLUTE_EVAP_SYS_VAPOR_PRESSURE 0x53
#define PID_EVAP_SYS_VAPOR_PRESSURE2 0x54
#define PID_SHORT_TERM_SECONDARY_O2_TRIM_1 0x55
#define PID_LONG_TERM_SECONDARY_O2_TRIM_1 0x56
#define PID_SHORT_TERM_SECONDARY_O2_TRIM_2 0x57
#define PID_LONG_TERM_SECONDARY_O2_TRIM_2 0x58
#define PID_FUEL_RAIL_ABSOLUTE_PRESSURE 0x59
#define PID_RELATIVE_ACCELERATOR_PEDAL_POS 0x5A
#define PID_HYBRID_BATTERY_REMAINING 0x5B
#define PID_ENGINE_OIL_TEMP 0x5C
#define PID_FUEL_INJECTION_TIMING 0x5D
#define PID_ENGINE_FUEL_RATE 0x5E
#define PID_EMISSION_REQUIREMENTS 0x5F

// Transmission & Drivetrain
#define PID_DEMANDED_ENGINE_TORQUE 0x61
#define PID_ACTUAL_ENGINE_TORQUE 0x62
#define PID_ENGINE_REFERENCE_TORQUE 0x63
#define PID_ENGINE_PERCENT_TORQUE_DATA 0x64
#define PID_AUXILIARY_INPUT_OUTPUT_SUPPORTED 0x65
#define PID_MASS_AIR_FLOW_SENSOR 0x66
#define PID_ENGINE_COOLANT_TEMP 0x67
#define PID_INTAKE_AIR_TEMP_SENSOR 0x68
#define PID_COMMANDED_EGR_AND_EGR_ERROR 0x69
#define PID_COMMANDED_DIESEL_INTAKE_AIR_FLOW 0x6A
#define PID_EGR_TEMPERATURE 0x6B
#define PID_COMMANDED_THROTTLE_ACTUATOR_CONTROL 0x6C
#define PID_FUEL_PRESSURE_CONTROL_SYSTEM 0x6D
#define PID_INJECTION_PRESSURE_CONTROL_SYSTEM 0x6E
#define PID_TURBOCHARGER_COMPRESSOR_INLET_PRESSURE 0x6F

// Turbo & Boost Control
#define PID_BOOST_PRESSURE_CONTROL 0x70
#define PID_VARIABLE_GEOMETRY_TURBO_CONTROL 0x71
#define PID_WASTEGATE_CONTROL 0x72
#define PID_EXHAUST_PRESSURE 0x73
#define PID_TURBOCHARGER_RPM 0x74
#define PID_TURBOCHARGER_TEMP_1 0x75
#define PID_TURBOCHARGER_TEMP_2 0x76
#define PID_CHARGE_AIR_COOLER_TEMP 0x77
#define PID_EXHAUST_GAS_TEMP_BANK_1 0x78
#define PID_EXHAUST_GAS_TEMP_BANK_2 0x79
#define PID_DIESEL_PARTICULATE_FILTER_1 0x7A
#define PID_DIESEL_PARTICULATE_FILTER_2 0x7B
#define PID_DIESEL_PARTICULATE_FILTER_TEMP 0x7C
#define PID_NOX_NTE_CONTROL_AREA_STATUS 0x7D
#define PID_PM_NTE_CONTROL_AREA_STATUS 0x7E
#define PID_ENGINE_RUN_TIME 0x7F

// Additional PID definitions for compatibility
#define PID_GPS_LATITUDE 0x20
#define PID_GPS_LONGITUDE 0x21
#define PID_GPS_SATELLITES 0x22

// Custom hardware sensor PIDs (using unused range)
#define PID_BATTERY_VOLTAGE 0x42  // Reusing control module voltage
#define PID_AMBIENT_TEMPERATURE 0x46  // Standard ambient air temp
#define PID_ENGINE_PRESSURE 0x43  // Reusing absolute load value for oil pressure

#endif // CONFIG_H
